version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    expose:
      - 5432
  app:
    build: ./app
    container_name: nestapi
    ports:
      - 3000:3000
    expose:
      - 3000